org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Flask 后端地址：
#  - 生产环境（当前）：http://8.146.225.19:5000
#  - 模拟器访问本机 Flask：http://10.0.2.2:5000
#  - 真机局域网调试：http://<电脑局域网IP>:5000
moci.baseUrl=http://8.145.53.212:5000

# 后端是 http（无 TLS）时设为 true；https 部署务必设为 false
moci.cleartext=true
