"""PostgreSQL 连接与表结构。SQL 仍可用 SQLite 风格的 `?` 占位符。"""

from __future__ import annotations

import os
import re
from typing import Any, Sequence

import psycopg
from psycopg.rows import dict_row

DEFAULT_DATABASE_URL = "postgresql://moci:moci@127.0.0.1:5432/moci"


def database_url() -> str:
    url = (os.environ.get("DATABASE_URL") or "").strip() or DEFAULT_DATABASE_URL
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://") :]
    return url


def _adapt_sql(sql: str) -> str:
    sql = re.sub(r"(?<![:\w]):([A-Za-z_][A-Za-z0-9_]*)", r"%(\1)s", sql)
    return sql.replace("?", "%s")


class Database:
    def __init__(self, conn: psycopg.Connection):
        self._conn = conn

    def execute(self, sql: str, params: Sequence[Any] | dict | None = None):
        sql = _adapt_sql(sql)
        if params is None:
            return self._conn.execute(sql)
        if isinstance(params, dict):
            return self._conn.execute(sql, params)
        return self._conn.execute(sql, tuple(params))

    def executescript(self, script: str) -> None:
        for raw in script.split(";"):
            stmt = raw.strip()
            if stmt:
                self.execute(stmt)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


def connect() -> Database:
    try:
        conn = psycopg.connect(database_url(), row_factory=dict_row)
    except psycopg.Error as exc:
        raise RuntimeError(
            "无法连接 PostgreSQL。请设置 DATABASE_URL，"
            f"或启动本地库（默认 {DEFAULT_DATABASE_URL}）。\n{exc}"
        ) from exc
    return Database(conn)


def _tables(db: Database) -> set[str]:
    rows = db.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
        """
    ).fetchall()
    return {row["table_name"] for row in rows}


def _columns(db: Database, table: str) -> set[str]:
    rows = db.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = ?
        """,
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _add_column(db: Database, table: str, column: str, ddl: str) -> None:
    if column not in _columns(db, table):
        db.execute(f"ALTER TABLE {table} ADD COLUMN {ddl}")


def reset_id_sequence(db: Database, table: str) -> None:
    row = db.execute(f"SELECT COALESCE(MAX(id), 0) AS n FROM {table}").fetchone()
    n = int(row["n"] or 0)
    db.execute(
        "SELECT setval(pg_get_serial_sequence(?, 'id'), ?, ?)",
        (f"public.{table}", max(n, 1), n > 0),
    )


def init_schema(db: Database) -> None:
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            status TEXT NOT NULL DEFAULT 'pending',
            daily_words INTEGER NOT NULL DEFAULT 8,
            daily_review INTEGER NOT NULL DEFAULT 8,
            know_speak INTEGER NOT NULL DEFAULT 1,
            know_spell INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        )
        """
    )
    _add_column(db, "users", "role", "role TEXT NOT NULL DEFAULT 'user'")
    _add_column(db, "users", "status", "status TEXT NOT NULL DEFAULT 'pending'")
    _add_column(db, "users", "daily_words", "daily_words INTEGER NOT NULL DEFAULT 8")
    _add_column(
        db, "users", "daily_review", "daily_review INTEGER NOT NULL DEFAULT 8"
    )
    _add_column(db, "users", "know_speak", "know_speak INTEGER NOT NULL DEFAULT 1")
    _add_column(db, "users", "know_spell", "know_spell INTEGER NOT NULL DEFAULT 1")

    db.execute(
        """
        CREATE TABLE IF NOT EXISTS words (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            term TEXT NOT NULL,
            phonetic TEXT NOT NULL DEFAULT '',
            pos TEXT NOT NULL DEFAULT '',
            meaning TEXT NOT NULL,
            phrase TEXT NOT NULL DEFAULT '',
            example TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    _add_column(db, "words", "phrase", "phrase TEXT NOT NULL DEFAULT ''")
    _add_column(db, "words", "pos", "pos TEXT NOT NULL DEFAULT ''")

    db.execute(
        """
        CREATE TABLE IF NOT EXISTS progress (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'new',
            review_count INTEGER NOT NULL DEFAULT 0,
            correct_streak INTEGER NOT NULL DEFAULT 0,
            last_reviewed TEXT,
            next_review TEXT,
            updated_at TEXT NOT NULL,
            UNIQUE (user_id, word_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS review_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
            rating TEXT NOT NULL,
            kind TEXT NOT NULL DEFAULT 'new',
            created_at TEXT NOT NULL
        )
        """
    )
    _add_column(db, "review_logs", "kind", "kind TEXT NOT NULL DEFAULT 'new'")
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS parent_children (
            parent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            child_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TEXT NOT NULL,
            PRIMARY KEY (parent_id, child_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS daily_results (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            study_date TEXT NOT NULL,
            new_quota INTEGER NOT NULL DEFAULT 0,
            review_quota INTEGER NOT NULL DEFAULT 0,
            new_done INTEGER NOT NULL DEFAULT 0,
            review_done INTEGER NOT NULL DEFAULT 0,
            new_n INTEGER NOT NULL DEFAULT 0,
            review_n INTEGER NOT NULL DEFAULT 0,
            easy_n INTEGER NOT NULL DEFAULT 0,
            again_n INTEGER NOT NULL DEFAULT 0,
            reviews INTEGER NOT NULL DEFAULT 0,
            completed INTEGER NOT NULL DEFAULT 0,
            first_at TEXT,
            last_at TEXT,
            updated_at TEXT NOT NULL,
            UNIQUE (user_id, study_date)
        )
        """
    )
    db.execute("CREATE INDEX IF NOT EXISTS idx_words_term ON words (term)")
    db.execute(
        "CREATE INDEX IF NOT EXISTS idx_progress_due ON progress (user_id, next_review)"
    )
    db.execute(
        "CREATE INDEX IF NOT EXISTS idx_review_logs_day ON review_logs (user_id, created_at)"
    )
    db.execute(
        "CREATE INDEX IF NOT EXISTS idx_daily_results_date ON daily_results (study_date)"
    )

    admin_n = db.execute(
        "SELECT COUNT(*) AS n FROM users WHERE role = ?", ("admin",)
    ).fetchone()["n"]
    if admin_n == 0:
        first = db.execute(
            "SELECT id FROM users ORDER BY id ASC LIMIT 1"
        ).fetchone()
        if first:
            db.execute(
                "UPDATE users SET role = ? WHERE id = ?",
                ("admin", first["id"]),
            )
    db.commit()
