services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: moci
      POSTGRES_USER: moci
      POSTGRES_PASSWORD: moci
    ports:
      - "5432:5432"
    volumes:
      - moci_pg:/var/lib/postgresql/data

volumes:
  moci_pg:
